#!/bin/bash

function node-get-system-upgrade {
  sudo apt update
  sudo NEEDRESTART_MODE=a apt-get dist-upgrade -y
}

function node-get-add-flathub {
  sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
}

function node-get-install {
  sudo apt update
  sudo apt install -y $1 2> /dev/null || sudo flatpak install -y $1 || sudo snap install $1 || echo "Package not found."
}

function node-get-remove {
  sudo apt remove -y $1 2> /dev/null || sudo flatpak uninstall -y $1 || sudo snap remove $1 || echo "Package not found."
}

if [ $# -eq 0 ]; then
  echo "node-get: Pseudo-Package Manager for F-Stop Linux"
  echo "Usage: node-get <command> <package>"
  echo "Commands:"
  echo "  system-upgrade   upgrade system packages using apt upgrade"
  echo "  install          install a package using apt install or flatpak install"
  echo "  remove           remove a package using apt remove or flatpak uninstall"
  echo "  add-flathub      add the Flathub repository to Flatpak"
  exit 1
fi

if [ ! "$(command -v flatpak)" ]; then
  echo "Error: flatpak not found. Installing..."
  sudo apt install flatpak -y
fi

if [ ! "$(command -v snap)" ]; then
  echo "Error: snap not found. Installing..."
  sudo apt install snapd -y
fi

if [ "$1" = "system-upgrade" ]; then
  node-get-system-upgrade
elif [ "$1" = "install" ]; then
  node-get-install $2
elif [ "$1" = "remove" ]; then
  node-get-remove $2
elif [ "$1" = "add-flathub" ]; then
  node-get-add-flathub
else
  echo "Error: Unrecognized command"
  exit 1
fi
