#!/bin/bash

function node-get-system-upgrade {
  sudo apt update
  echo "Preparing packages..."
  sudo dpkg --add-architecture i386
  sudo apt update
  echo "Ensuring the important stuff's up-to-date..."
  sudo apt-get upgrade

  sudo rm /usr/bin/node-get
  sudo wget -O /usr/bin/node-get https://raw.githubusercontent.com/F-Stop-Technologies/node-get/main/node-get
  sudo chmod +x /usr/bin/node-get

  sudo rm /usr/bin/nvidia-easyinstall
  sudo wget -O /usr/bin/nvidia-easyinstall https://raw.githubusercontent.com/F-Stop-Technologies/nvidia-installer/main/nvidia-easyinstall
  sudo chmod +x /usr/bin/nvidia-easyinstall

  sudo rm /fstop-wallpapers/  || echo "Wallpapers not installed yet, not reinstalling but installing."
  sudo git clone https://github.com/F-Stop-Technologies/wallpapers /fstop-wallpapers/
  sudo chmod -R 777 /fstop-wallpapers

  sudo mkdir /fstop-python-nodefun/
  sudo wget -O /fstop-python-nodefun/duckbart.py https://raw.githubusercontent.com/F-Stop-Technologies/duckbart-fstop/main/main.py
  sudo wget -O /fstop-python-nodefun/blog-gen.py https://raw.githubusercontent.com/F-Stop-Technologies/blogger_openai_fstop/main/main.py

  sudo rm /fstop-python-folderimagedetection/ || echo "Image detection not installed yet, not reinstalling but installing."
  sudo git clone https://github.com/F-Stop-Technologies/yolov8-fstop /fstop-python-folderimagedetection/
  sudo wget -O /fstop-python-folderimagedetection/recognize.py https://raw.githubusercontent.com/F-Stop-Technologies/yolov8-imageobjectdetection/main/detect.py
  sudo wget -O /fstop-python-folderimagedetection/yolov8n.pt https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt

  sudo apt install -y python3-torch python3-tk python3-numpy python3-torchvision

  sudo -u $USER pip3 install openai duckduckgo3 requests python-dotenv colorama --break-system-packages
  sudo -u $USER pip3 install opencv-python --break-system-packages
  sudo -u $USER pip3 install ultralytics --break-system-packages || echo "Error installing ultralytics, you won't be able to use image detection!"
}

function node-get-add-flathub {
  sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
}

function node-get-install {
  sudo apt update
  sudo apt install -y $1 2> /dev/null || sudo flatpak install -y $1 || sudo snap install $1 || echo "Package not found."
}

function node-get-remove {
  sudo apt remove -y $1 2> /dev/null || sudo flatpak uninstall -y $1 || sudo snap remove $1 || echo "Package not found."
}

if [ $# -eq 0 ]; then
  echo "node-get: Pseudo-Package Manager for F-Stop Linux"
  echo "Usage: node-get <command> <package>"
  echo "Commands:"
  echo "  system-upgrade   upgrade system packages using apt dist-upgrade (do this once a week)"
  echo "  install          install a package using apt install or flatpak install"
  echo "  remove           remove a package using apt remove or flatpak uninstall"
  echo "  add-flathub      add the Flathub repository to Flatpak"
  exit 1
fi

if [ ! "$(command -v flatpak)" ]; then
  echo "Error: flatpak not found. Installing..."
  sudo apt install flatpak -y
fi

if [ ! "$(command -v snap)" ]; then
  echo "Error: snap not found. Installing..."
  sudo apt install snapd -y
fi

if [ "$1" = "system-upgrade" ]; then
  node-get-system-upgrade
elif [ "$1" = "install" ]; then
  node-get-install $2
elif [ "$1" = "remove" ]; then
  node-get-remove $2
elif [ "$1" = "add-flathub" ]; then
  node-get-add-flathub
else
  echo "Error: Unrecognized command"
  exit 1
fi

